
spring.application.name=file-storage-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/file_storage?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=fs_user
spring.datasource.password=12345

minio.endpoint=http://localhost:9000
minio.access-key=testadmin
minio.secret-key=test12345
minio.bucket=file-storage
minio.region=us-east-1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

springdoc.swagger-ui.persistAuthorization=true
springdoc.swagger-ui.path=/swagger-ui

management.endpoints.web.exposure.include=health,info

security.admin-api-key=fikir-coworking-2026

storage.provider=minio
storage.local.base-path=./data/files